### ISSUE TITLE
DMS vs DD

### ISSUE THREAD

**Issue by Flamewires** [proto17/HelicopterDemod#1]
Coords are off because they are DMS not DD. 
https://www.latlong.net/degrees-minutes-seconds-to-decimal-degrees
![Screenshot from 2020-05-30 12-07-51](https://user-images.githubusercontent.com/455135/83333396-3bb45e00-a26e-11ea-8734-f24bcd17da06.png)

**Comment by proto17** [comment]
Thank you for helping out!!

In the below example, if the format is DMS would the expected values be D=`104` M=`58` and S=`80`?  The S value shouldn't exceed 60 right?  Or is the S value found with something like `60 * (S / 100)`?

```
AN 39 4404
BW 104 5880
C260
D061
E001164
K00000
L2605
l06680
```

Apologies if I'm missing something obvious.  Not well versed in coordinate systems O.O

**Comment by proto17** [comment]
Poking around on https://www.pgc.umn.edu/apps/convert/ makes me think is DDM with the above example being 39 degrees 44.04 minutes and -104 degrees 58.8 minutes.  Does that make any sense or am I making this a lot harder than it need be?

**Comment by proto17** [comment]
Converting with the following function seems to produce what at least appears to be valid data:

```
def convert(part_one, part_two):
    degrees = int(part_one)
    minutes = int(part_two[:2])
    seconds = (int(part_two[2:]) / 100.0) * 60

    return degrees + (minutes / 60.0) + (seconds / 3600)
```

Examples calls being `convert('39','4404')` and `convert('104','5880')`

**Comment by proto17** [comment]
![](https://i.imgur.com/R1ktUeh.png)

**Comment by proto17** [comment]
The code that generated the ring above is in PR #2.  Let me know if you think that's correct.
