### ISSUE TITLE
Colorblindness

### ISSUE THREAD

**Issue by connornishijima** [proto17/HelicopterDemod#3]
Hey proto17! Saw [your article on Hackaday](https://hackaday.com/2020/05/31/pulling-data-from-news-feed-telemetry) and I have something to note:

https://github.com/proto17/HelicopterDemod/wiki

In your Baudline images you're referring to a "blue" channel, but the lines are green and magenta for me! For reference, the colors of the lines in those images are:

**Green:**      [rgb(0, 237, 0)](https://www.color-hex.com/color/00ed00)
(Appears green)

**"Blue":**      [rgb(170, 0, 237)](https://www.color-hex.com/color/aa00ed)
(mathematically a purple-ish magenta - this one has the 1200Hz-bandwidth signal)

For comparison, here is a link showing **rgb(237,170,0)** (swapped color channels) to show how distant that "170" takes the color from pure "red":

https://www.color-hex.com/color/edaa00

Does one of us have a colorblindness issue? It's a tricky question, as you can't describe a color to someone who hasn't seen it.

**Comment by proto17** [comment]
I figured I was gonna get outed when I wrote that up lol  Thanks for pointing it out!  I updated the page :)

**Comment by liamengland1** [comment]
https://github.com/proto17/HelicopterDemod/wiki/Home/_compare/2df867da27d9fac9143862de748786765601aeba...8d5f0d77e0d8504c81214dcaf8edfd85b95e0ddf

**Comment by connornishijima** [comment]
No problem, buddy! :) You can close this issue now.
